// src/app/components/Table.tsx
interface TableProps {
  heading: string
  inside: string
}

export default function Table(props: TableProps) {
  return (
    <div className="font-sans mt-10">
      <header className="text-5xl bold">
        <h1>{props.heading}</h1>
      </header>
      <br></br>
      <main className="@apply w-[860px] p-[25px] rounded-[15px] border-r-[10px] border-b-[10px] border-2 border-solid border-amber-400 text-xl">
        <p>{props.inside}</p>
      </main>
    </div>
  )
}

// SvelteHW4/my-app/src/lib/Table.svelte
<script lang="ts">
    export let heading: string
    export let inside: string
</script>

<header>
    <h1>{heading}</h1>
</header>
<main>
    <p>
        {inside}
    </p>
</main>

<style>
    main {
        border: 2px solid black;
        border-radius: 15px;
        padding: 25px;
        border-right-width: 10px;
        border-bottom-width: 10px;
        width: 860px;
    }
</style>
