// SvelteHW4/my-app/src/lib/Contact.svelte
<script lang="ts">
    export let action : string
    export let text : string
</script>

<form action={action}>
    <button id="from">
        <b>{text}</b>
    </button>
</form>   

<style>
    #from {
        color: black;
        height:50px;
        width:130px;
        border-radius: 8px;
        background-color: white;
        border: 2px solid black;
        transition-duration: 0.4s;
        margin-bottom: 15px;
    }
    #from:hover {
        border: 2px solid black;
        background-color: black;
        color: white;
    }
</style>

// src/app/components/Contact.tsx
interface ContactProps {
  action: string
  text: string
}
export default function Contact(props: ContactProps) {
  return (
    <form action={props.action}>
      <button
        id="from"
        className="@apply text-[black] h-[50px] w-[130px] bg-[white] duration-[0.4s] mb-[15px] rounded-lg border-2 border-solid border-amber-400 hover:bg-amber-400 hover:text-[white] hover:border-2 hover:border-solid hover:border-amber-400 font-semibold"
      >
        {props.text}
      </button>
    </form>
  )
}
